import { notFound } from 'next/navigation';

import { fetchOrderByAccessToken } from '@/lib/services/order-service';
import {
  fetchPhotosByIds,
  fetchPublicAlbum,
  fetchPublicStudioBySlug,
} from '@/lib/services/public-service';

import { OrderDownloadClient } from './order-download-client';

interface Props {
  params: Promise<{ token: string }>;
}

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Suas fotos',
};

/**
 * Direct, token-gated access page. The customer follows the link
 * generated by the studio (also visible in `/minhas-compras` after a
 * phone lookup). We resolve the order server-side so a guessed URL
 * never sees the studio's metadata, and only paid orders surface the
 * download CTA.
 *
 * For album items we expand `photoIds → PhotoDoc[]` so the bulk-
 * download button can hit every Storage object directly.
 */
export default async function OrderDownloadPage({ params }: Props) {
  const { token } = await params;
  const order = await fetchOrderByAccessToken(token);
  if (!order || order.status !== 'paid') notFound();

  const studio = await fetchPublicStudioBySlug(order.studioSlug);
  if (!studio) notFound();

  // Resolve every billable line into the set of PhotoDocs the
  // customer is allowed to download. For album items we fan out to
  // the album doc's `photoIds`; for photo items we just take the id.
  const albumItems = order.items.filter((item) => item.type === 'album');
  const photoItems = order.items.filter((item) => item.type === 'photo');

  const albumPhotoIdSets = await Promise.all(
    albumItems.map(async (item) => {
      const album = await fetchPublicAlbum(item.itemId);
      return album?.photoIds ?? [];
    }),
  );

  const allPhotoIds = Array.from(
    new Set([
      ...photoItems.map((item) => item.itemId),
      ...albumPhotoIdSets.flat(),
    ]),
  );
  const photos = await fetchPhotosByIds(allPhotoIds);

  return (
    <OrderDownloadClient
      order={order}
      studio={{
        id: studio.id,
        name: studio.name,
        slug: studio.slug,
        logoUrl: studio.logoUrl ?? null,
      }}
      photos={photos}
    />
  );
}
